### ISSUE TITLE
Button "Close"

### ISSUE THREAD

**Issue by Florian-COLLIN** [AirSThib/Primus#1]
Hello,

On my computer, the "Close" button, usually indicated by a cross, is indicated like this: Ä.

Regards,

Florian COLLIN

**Comment by Athozus** [comment]
Can you send a screenshot please ?

**Comment by Florian-COLLIN** [comment]
I don't see how to put a screenshot.

**Comment by Athozus** [comment]
There is a sentence in the bottom of the editor, click on it ;)

**Comment by Florian-COLLIN** [comment]
![Capture_28](https://user-images.githubusercontent.com/73430474/114311527-6ce8f600-9aef-11eb-87d9-923c8c4af05a.PNG)

**Comment by Athozus** [comment]
o_O

First I see that the requested font is not used, I'll check it. And maybe I didn't define it as UTF-8 correctly, I'll check it too.

**Comment by Athozus** [comment]
Can you try it now (re-download) ?

**Comment by Florian-COLLIN** [comment]
This is what it looks like now !

![Capture_29](https://user-images.githubusercontent.com/73430474/114313469-f223d900-9af6-11eb-8065-607bf916dbee.PNG)

**Comment by Athozus** [comment]
Okay, I think I understand. The font-face property doesn't exist in the QSS. I'll check it.

**Comment by Athozus** [comment]
I used another method, I tested the new executable, normally it works.

**Comment by Florian-COLLIN** [comment]
The rendering is different, but it remains without seeing the name of the software as well as the result of the calculation.

![Capture_30](https://user-images.githubusercontent.com/73430474/114314906-ecc98d00-9afc-11eb-923f-eeca212c273b.PNG)

**Comment by Athozus** [comment]
Ah that's a problem in the QSS file, let me check it.

**Comment by Athozus** [comment]
OK, I checked on my own computer, it's correct now. The main problem that the `style.qss` file was not in the `.exe` directory !

**Comment by Athozus** [comment]
Did you tested it again (check the release again) ?

**Comment by Florian-COLLIN** [comment]
Everything is OK
