### ISSUE TITLE
I've a problem with the .txt file on Windows

### ISSUE THREAD

**Issue by Felsog31** [AirSThib/Primus#4]
The basic notepad of Windows show this :

⌣⌣⌣⌣⌣⌣⌣⌣⌣⌣⌣⌣⌣ †䜠湥牥瑡摥戠⁹牐浩獵 湯㈠㈰ⴱ㐰ㄭ吳〱㔺㨱㌵ㄮ〱ਗ਼牆浯›ਲ潔›〱〰⌊⌣⌣⌣⌣⌣⌣⌣⌣⌣⌣⌣⌣ਣਊਲਲ਼ਵ਷ㄱㄊਲ਼㜱ㄊਹ㌲㈊ਹㄳ㌊਷ㄴ㐊ਲ਼㜴㔊ਲ਼㤵㘊਱㜶㜊਱㌷㜊ਹ㌸㠊ਹ㜹ㄊ㄰ㄊ㌰ㄊ㜰ㄊ㤰ㄊ㌱ㄊ㜲ㄊㄳㄊ㜳ㄊ㤳ㄊ㤴ㄊㄵㄊ㜵ㄊ㌶ㄊ㜶ㄊ㌷ㄊ㤷ㄊㄸㄊㄹㄊ㌹ㄊ㜹ㄊ㤹㈊ㄱ㈊㌲㈊㜲㈊㤲㈊㌳㈊㤳㈊ㄴ㈊ㄵ㈊㜵㈊㌶㈊㤶㈊ㄷ㈊㜷㈊ㄸ㈊㌸㈊㌹㌊㜰㌊ㄱ㌊㌱㌊㜱㌊ㄳ㌊㜳㌊㜴㌊㤴㌊㌵㌊㤵㌊㜶㌊㌷㌊㤷㌊㌸㌊㤸㌊㜹㐊㄰㐊㤰㐊㤱㐊ㄲ㐊ㄳ㐊㌳㐊㤳㐊㌴㐊㤴㐊㜵㐊ㄶ㐊㌶㐊㜶㐊㤷㐊㜸㐊ㄹ㐊㤹㔊㌰㔊㤰㔊ㄲ㔊㌲㔊ㄴ㔊㜴㔊㜵㔊㌶㔊㤶㔊ㄷ㔊㜷㔊㜸㔊㌹㔊㤹㘊㄰㘊㜰㘊㌱㘊㜱㘊㤱㘊ㄳ㘊ㄴ㘊㌴㘊㜴㘊㌵㘊㤵㘊ㄶ㘊㌷㘊㜷㘊㌸㘊ㄹ㜊㄰㜊㤰㜊㤱㜊㜲㜊㌳㜊㤳㜊㌴㜊ㄵ㜊㜵㜊ㄶ㜊㤶㜊㌷㜊㜸㜊㜹㠊㤰㠊ㄱ㠊ㄲ㠊㌲㠊㜲㠊㤲㠊㤳㠊㌵㠊㜵㠊㤵㠊㌶㠊㜷㠊ㄸ㠊㌸㠊㜸㤊㜰㤊ㄱ㤊㤱㤊㤲㤊㜳㤊ㄴ㤊㜴㤊㌵㤊㜶㤊ㄷ㤊㜷㤊㌸㤊ㄹ㤊㜹ਊ慃捬汵瑡湩⁧湥敤⁤〲ㄲ〭ⴴ㌱ㅔ㨰ㄵ㔺⸳㔱娷ਊ⌣⌣⌣⌣⌣⌣⌣⌣䔊慸業慮整㩤㤠㤹䘊畯摮›㘱ਸ敐捲湥慴敧›㘱㠮㜱ਊ湅敤⁤〲ㄲ〭ⴴ㌱ㅔ㨰ㄵ㔺⸳㐲娸

But when I open the file with VS Code, the problem is solved.

**Comment by Athozus** [comment]
I think that's a problem with the UTF-8.
